# Page settings
baseurl = "https://mntnr.io"
title = "Maintainer Mountaineer"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Richard Littauer"
  description = "Navigating the mountain of Open Source maintenance work"
  email = "richard@mntnr.io"
  twitter = "https://twitter.com/richlitt"
  github = "https://github.com/mntnr"
  # Navigation
  [params.navigation]
    brand = "Maintainer.io"
    home = "Home"
    developers = "Developers"
    testimonials = "Testimonials"
    services = "Organizations"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Scale Open Source Maintenance"
    subtitle = "We help maintain your GitHub projects for you, allowing you more time to focus on what you want"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Streamline your GitHub"
    description = "We've built tools to streamline your GitHub repository or organization, making it easier for new users to become great contributors. From contributing.md to standard readmes, we can help your repo shine."
    url = "#"
    button = "Go Open Source"
    icon = "icon-github"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Got Issues?"
    description = "We'll help you triage and manage your issues and pull requests, providing you with empathetic copy and templates for recurring questions. And we'll pen human responses when you don't want to, letting you sleep easier."
    url = "#"
    button = "See our plans"
    icon = "icon-exclamation-circle"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Community Dashboard"
    description = "Use our dashboard to track your community over time, to provide data-based feedback about how you can grow, get more open source contributions, and spend less time maintaining and more time creating."
    url = "#"
    button = "Why us?"
    icon = "icon-graph"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Prefer video to text?"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Developers section
  [params.developers]
    enable = true
    title = "Solo Developer?"
    description = "We've got you covered."

    [[params.developers.item]]
      title = "GitHub maintenance"
      description = "We've built tools and processes to help maintain your GitHub repositories and organization, making it easy for newcomers to contribute to your code, and stay on as community members"
      icon = "icon-github"

    [[params.developers.item]]
      title = "Issue Triage"
      description = "We'll help you triage and manage open issues and pull requests, providing you with copy and templates for recurring questions. Take the stress out of user demands."
      icon = "icon-exclamation-circle"

    [[params.developers.item]]
      title = "Community Dashboards"
      description = "Track your community over time, to provide data-based feedback about how you can grow and get more open source contributions."
      icon = "icon-graph"

    [[params.developers.item]]
      title = "Open Sourcing"
      description = "Want to make your project open source, but don't know how? We'll help you modularize the code, and outline a strategy getting people excited about your code"
      icon = "icon-sign"

  # Work section
  # [params.work]
  #   enable = false
  #   title = "Work"
  #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #   footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'
  #
  #   [[params.work.row]]
  #     img = "work_1.jpg"
  #     alt = "Image2"
  #     title = "Project 1"
  #     subtitle = "Branding"
  #
  #   [[params.work.row]]
  #     img = "work_2.jpg"
  #     alt = "Image2"
  #     title = "Project 2"
  #     subtitle = "Design"
  #
  #   [[params.work.row]]
  #     img = "work_3.jpg"
  #     alt = "Image3"
  #     title = "Project 3"
  #     subtitle = "Design"
  #
  #   [[params.work.row]]
  #     img = "work_4.jpg"
  #     alt = "Image4"
  #     title = "Project 4"
  #     subtitle = "Design"
  #
  #   [[params.work.row]]
  #     img = "work_5.jpg"
  #     alt = "Image5"
  #     title = "Project 5"
  #     subtitle = "Design"
  #
  #   [[params.work.row]]
  #     img = "work_6.jpg"
  #     alt = "Image6"
  #     title = "Project 6"
  #     subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    # description = "Some feedback from people who've worked with us."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Roberta Voulon, <a href="http://www.pitonneux.com/" target="_blank">Les Pitonneux</a> <span class="subtext">Founder</span>'
      img = "roberta.jpg"
      alt = "Roberta Voulon of Les Pitonneux"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "Richard has helped us identify numerous contribution-smells: where our project structure, onboarding, and contribution guidelines are inhibiting new users and participants from joining."
      person = 'Simon Vansintjan, Contributor to <a href="http://opensourcedesign.net/" target="_blank">Open Source Design</a>'
      img = "simon.jpg"
      alt = "Simon Vansintjan"




  # Services section
  [params.services]
    enable = true
    title = "Larger Organization?"
    description = "We can help you maintain and market your Open Source organization."

    [[params.services.item]]
      title = "GitHub maintenance"
      description = "We've built tools and processes to help maintain your GitHub repositories and organization, making it easy for newcomers to contribute to your code, and stay on as community members"
      icon = "icon-github"

    [[params.services.item]]
      title = "Issue Triage"
      description = "We'll help you triage and manage open issues and pull requests, providing you with copy and templates for recurring questions. Take the stress out of user demands."
      icon = "icon-exclamation-circle"

    [[params.services.item]]
      title = "Community Dashboards"
      description = "Track your community over time, to provide data-based feedback about how you can grow and get more open source contributions."
      icon = "icon-graph"

    [[params.services.item]]
      title = "Open Sourcing"
      description = "Want to make your project open source, but don't know how? We'll help you modularize the code, and outline a strategy getting people excited about your code"
      icon = "icon-sign"

  # About section
  [params.about]
    enable = true
    title = "Our Humans"
    description = "We're an experienced, diverse team of open source coders, writers, and humans."

    [[params.about.item]]
      name = "Richard Littauer"
      position = "JavaScript Adventurer"
      description = "Richard is happiest coding from a ski lodge on top of a mountain. He's dedicated to building fantastic READMEs and growing communities."
      img = "richard.jpg"
      alt = "Richard Littauer"
      social = [
        ["icon-twitter", "https://twitter.com/richlitt"],
        ["icon-github", "https://github.com/RichardLitt"],
        ["icon-envelope", "mailto:richard@maintainer.io"]
      ]

    [[params.about.item]]
      name = "Gabi Ciudin"
      position = "Developer"
      description = "Gabi codes from whatever train, bus, or hostel she happens to be in while travelling. She comes from the .NET world, bringing an important closed-source perspective to the team."
      img = "gabi.jpg"
      alt = "Gabi Ciudin"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/gabi-ciudin/"],
        ["icon-github", "https://github.com/gabiciudin"]
      ]

    [[params.about.item]]
      name = "Amna Shamim"
      position = "Writer"
      description = "Amna is a freelancer writer, with work in HuffPo, Entrepreneur, and Business Insider. As a writer, she brings a creative eye to the documentation process."
      img = "amna.jpeg"
      alt = "Amna Shamim"
      social = [
        ["icon-twitter", "https://twitter.com/amnashamimnyc"],
        ["icon-globe", "http://www.amnashamim.com/"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "READMEs standardized"
      icon = "icon-briefcase"
      from = 0
      to = 700
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "GitHub Organizations So Far"
      icon = "icon-code"
      from = 0
      to = 12
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Estimated Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1572
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Hypothetical Hours Saved"
      icon = "icon-people"
      from = 0
      to = 42000
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Get in touch"
    description = "Want more information? We're always an email away."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "The road. We are 100% remote."],
        ["icon-envelope", "richard@maintainer.io"],
        ["icon-globe", '<a href="https://maintainer.io" target="_blank">maintainer.io</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'Site licensed under a CC-BY-SA-NC 4.0 Unported License Â© <a href="https://burntfen.com" target="_blank">Burnt Fen Creative</a> 2017. <br /> Theme modified by <a href="https://github.com/RichardLitt" target="_blank" >@RichardLitt</a>, with original &copy; Elate Free HTML5 under a CC SA 3.0 License, with Hugo port by <a href="https://github.com/saey55" target="_blank">@saey55</a>.'
